# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: build
  jobs:
  - job: job_a
    steps:
    - bash: echo "step a"
      displayName: 'run echo1'
    - bash: echo "step b" > "$(Build.ArtifactStagingDirectory)/aa.txt"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'ar1'
- stage: test
  jobs: 
  - job: job_b
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
